name: OpenSSF Scorecard
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 14 * * 5'
permissions:
  contents: read
jobs:
  analysis:
    name: Scorecards analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ossf/scorecard-action@v2
        with:
          results_file: results.sarif
          results_format: sarif
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: scorecard-results
          path: results.sarif
      - name: Upload to GitHub code scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
