name: OpenSSF Scorecard

on:
  workflow_dispatch:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop  ]
  schedule:
    - cron: '15 14 * * 5'

permissions:
  contents: read
  security-events: write
  id-token: write

jobs:
  analysis:
    name: Scorecards analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ossf/scorecard-action@v3
        with:
          publish_results: true
          results_file: results.sarif
          results_format: sarif
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: scorecard-results
          path: results.sarif
      - name: Upload to GitHub code scanning
        uses: github/codeql-action/upload-sarif@v3.29.4
        with:
          sarif_file: results.sarif
